"""Subclass of GCodePanelTemplate, which is generated by wxFormBuilder."""

import wx
import splicer_GUI_FB

# Implementing GCodePanelTemplate
class splicer_GUIGCodePanelTemplate( splicer_GUI_FB.GCodePanelTemplate ):
	def __init__( self, parent ):
		splicer_GUI_FB.GCodePanelTemplate.__init__( self, parent )
	
