"""Subclass of TransitionPanelTemplate, which is generated by wxFormBuilder."""

import wx
import splicer_GUI_FB

# Implementing TransitionPanelTemplate
class splicer_GUITransitionPanelTemplate( splicer_GUI_FB.TransitionPanelTemplate ):
	def __init__( self, parent ):
		splicer_GUI_FB.TransitionPanelTemplate.__init__( self, parent )
	
