"""Subclass of GCodePanel, which is generated by wxFormBuilder."""

import wx
import templates

# Implementing GCodePanel
class GCodePanel( templates.GCodePanel ):
	# manually add constructor default arguments here to make it play nice with subclass feature in wxFB.
	def __init__( self, parent, id = wx.ID_ANY, pos = wx.DefaultPosition, size = wx.Size( -1,-1 ), style = wx.TAB_TRAVERSAL  ):
		templates.GCodePanel.__init__( self, parent )
	
	# Handlers for GCodePanel events.
	def OnFileSelected( self, event ):
		# TODO: Implement OnFileSelected
		pass
	
	
