"""Subclass of TransitionPanel, which is generated by wxFormBuilder."""

import wx
import templates

# Implementing TransitionPanel
class TransitionPanel( templates.TransitionPanel ):
	# manually add constructor default arguments here to make it play nice with subclass feature in wxFB.
	def __init__( self, parent, id = wx.ID_ANY, pos = wx.DefaultPosition, size = wx.Size( -1,-1 ), style = wx.TAB_TRAVERSAL ):
		templates.TransitionPanel.__init__( self, parent )
	
	# Handlers for TransitionPanel events.
	def OnCheckBox( self, event ):
		if self.useTransition_checkbox.IsChecked():
			self.filePicker.Enable()
			self.fileDisplay.Enable()
		else:
			self.filePicker.Disable()
			self.fileDisplay.Disable()
	
	def OnFileSelected( self, event ):
		# TODO: Implement OnFileSelected
		pass
	
	
